# Generated by Django 5.2.4 on 2025-07-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='availble_servings',
            new_name='available_servings',
        ),
    ]
